SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS universes;
DROP TABLE IF EXISTS types;
DROP TABLE IF EXISTS genders;
DROP TABLE IF EXISTS type_allowed_genders;
DROP TABLE IF EXISTS names;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS email_verification_tokens;
DROP TABLE IF EXISTS refresh_tokens;
DROP TABLE IF EXISTS password_reset_tokens;
DROP TABLE IF EXISTS favorites;

SET FOREIGN_KEY_CHECKS = 1;

